version: '3'

tasks:
#region Up Tasks
  create-cluster:
    desc: Create the k3d cluster
    cmds:
      - >-
        if k3d cluster list | grep -w "kagent-demo" >/dev/null 2>&1; then
          echo "k3d cluster 'kagent-demo' already exists; skipping create";
        else
          k3d cluster create --config k3d-config.yaml;
        fi
      # This is needed to merge the k3d kubeconfig into our default kubeconfig
      - KUBECONFIG=~/.kube/config k3d kubeconfig merge kagent-demo --kubeconfig-merge-default --kubeconfig-switch-context

  up:
    desc: Orchestrate the demo by creating the cluster
    cmds:
      - task: create-cluster
      - task: deploy

# TODO make render an orchestration task that depends on specific render tasks that way we can render in parallel
  render:
    desc: Render helmfile templates into single rendered-all.yaml files
    silent: true
    deps:
      - render-crds
    cmds:
      - |
        find ./manifests -name helmfile.yaml -type f -exec dirname {} \; | while read dir; do
          mkdir -p "$dir/rendered"
          (cd "$dir" && helmfile template > rendered/rendered-all.yaml)
        done

  render-crds:
    desc: Render CRD helmfiles into manifests/crds/rendered
    silent: true
    cmds:
      - |
        mkdir -p ./manifests/crds/rendered
        find ./manifests -name crd-helmfile.yaml -type f | while IFS= read -r file; do
          dir=$(dirname "$file")
          name=$(basename "$dir")
          helmfile -f "$file" template > "./manifests/crds/rendered/${name}-rendered-all.yaml"
        done

  deploy:
    desc: Apply rendered manifests via kustomize
    deps:
      - render
    cmds:
      - kubectl apply -f manifests/crds/rendered
      - kubectl wait --for=condition=established crd --all
      - kubectl apply -k manifests/
#endregion

#region Down Tasks
  delete-cluster:
    desc: Delete the k3d cluster
    cmds:
      - k3d cluster delete kagent-demo
      # Cleans up the kubeconfig entries
      - KUBECONFIG=~/.kube/config kubectl config delete-context k3d-kagent-demo
      - KUBECONFIG=~/.kube/config kubectl config delete-cluster k3d-kagent-demo
      - KUBECONFIG=~/.kube/config kubectl config delete-user admin@k3d-kagent-demo

  down:
    desc: Clean up by deleting the cluster
    deps:
      - clean-rendered
    cmds:
      - task: delete-cluster

  clean-rendered:
    desc: Remove all rendered directories under manifests
    cmds:
      - find ./manifests -type d -name rendered -exec rm -rf {} +
#endregion

  generate-envs:
    desc: Generate .env files from .env.example files in manifests directories if they don't exist
    silent: true
    cmds:
      - |
        bash -c '
        set -euo pipefail

        printf "🔍 Scanning for .env.example files in manifests directory...\n\n"

        generated_files=()
        skipped_files=()

        while IFS= read -r example_file; do
          env_file="${example_file%.example}"
          if [ ! -f "$env_file" ]; then
            cp "$example_file" "$env_file"
            generated_files+=("$env_file")
            printf "✅ \033[32mGenerated:\033[0m %s\n" "$env_file"
          else
            skipped_files+=("$env_file")
            printf "⏭️  \033[33mSkipped:\033[0m   %s (already exists)\n" "$env_file"
          fi
        done < <(find ./manifests -name .env.example -type f | sort)

        printf "\n📋 Summary:\n"
        printf "   \033[32mGenerated:\033[0m %d files\n" "${#generated_files[@]}"
        printf "   \033[33mSkipped:\033[0m   %d files\n" "${#skipped_files[@]}"

        if [ "${#generated_files[@]}" -gt 0 ]; then
          printf "\n⚠️  \033[31mAction Required:\033[0m Please edit the following files to add your actual values:\n"
          for file in "${generated_files[@]}"; do
            printf "   📝 %s\n" "$file"
          done
        fi
        '
